server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.com.smarthire=DEBUG
# ---------- Actuator ----------
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

# ---------- Application Info ----------
info.app.name=Smart Hire Auth Service
info.app.version=1.0.0
info.app.description=Authentication and Authorization Microservice